### PR TITLE
Jekyll Dev

### PR DESCRIPTION
**Pull request by themeix**

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
@themeix, what build command should we be using (per @vcavallo, currently it uses a js build, but we likely should switch to do the normal jekyll build command), and what is the output directory?

**Comment by thelifeandtimes** [comment]
Here is my design feedback. Going through the source content files now to see if I have any additional comments on the CRM side.

## Homepage
- [ ] Theres a weird behavior at the breakpoint. The page should always take up the full viewport. 
image
- [ ] The image should be centered in the viewport, rather than being indexed to the lefthand margin.

## Missives Index
- [ ] Page contents should disappear when they go into the nav bar 
image
- [ ] On mobile, the image should take the full viewport and content should parallax scroll over it, just like the behavior currently on desktop

## Missives Template
- [ ] `Return to Index` should go back to the missives index, rather than to the home page
- [ ] Author div has a bit too much of a gap between text and the section divider 
image

**## Experiments Index and Template Pages
- [ ] These currently 404, I think perhaps the button redirect needs some work?**

## General
- [ ] Fonts 
- [ ] Form entry needs to take some input. @thelifeandtimes to provide notion API for collecting that input
- [ ] Form on mobile in CTA section is stacking; let's truncate instead. it also loses it's border when tapped.
image
- [ ] Footer on mobile is stacking instead of compressing:
image
The 'mid-width' footer also is not aligned, so when fixing the stacking, this behavior should be checked as well: 
image

**Comment by thelifeandtimes** [comment]
## CMS Review
I've gone through the code to understand how content is getting pulled in. Providing comments here, plus some clarifying questions. @themeix, please let me know if you have any questions or need anything clarified further. 
- [ ] `_posts` and `_experiments` entries; it is my understanding that outside of the frontmatter, these will take either standard markdown, or the currently included HTML. Our default will be to write these posts in markdown, can you confirm that will function in the same manner as the current HTML? it needs to be able to support the following:
    - [ ] h1, h2, h3
    - [ ] callout box with image
    - [ ] full width image
    - [ ] constrained width image
    - [ ] body copy
    - [ ] inline `code`
    - [ ] codeblocks
    - [ ] bulleted list
    - [ ] numbered list
- [ ] we should have a `_author` directory that holds a set of authors who are then referenced based on the `author_name` frontmatter in a `_posts` .md file. the `author_images` frontmetter should be in the `_author` entry

### What do the following frontmatter elements do?
- [ ] "footer.yml"
    - [ ] `label`
    - [ ] `handlebars_url`
- [ ] "_experiments" 
    - [ ] `experiment_id`
    - [ ] `image` vs `bookmark_image`? if one of these is the background image, let's name it `bg_image`
    - [ ] `blog_post_full_image:` <- This looks like it is the image for the post contents. These should occur inline from the markdown where if an image url is provided in markdown format and a particular tag, they show up in either the "full" or "middle" formats.
    - [ ] `blog_post_middle_image:` <- This looks like it is the image for the post contents. These should occur inline from the markdown where if an image url is provided in markdown format and a particular tag, they show up in either the "full" or "middle" formats.

**Comment by thelifeandtimes** [comment]
I fixed the redirect for the Experiments Index and Experiments posts, so adding my feedback for those here:
## Experiments Index
- [ ] Page content should disappear behind the nav bar: 
image

- [ ] When hitting the breakpoint, the images are stretching to fill. Images should not stretch
image

- [ ] Button and Copy spacing needs to be increased: 
image


## Experiments Post
- [ ] image should be mapped to viewport size and center aligned
- [ ] When the page gets very narrow, the card contents overflow out of the card: 
image

- [ ] it appears that the `link` content both provides the text to appear on the button, as well prompts a `mailto:` dialog box. Let's break this into to items: `button_text` and `button_link` as we will likely want to present something like:
```
button_text: kisekaeindustries.com
button_link: https://kisekaeindustries.com/some-url
```

**Comment by themeix** [comment]
Thanks for your feebdack.. I am testing it again

**Pull request closed without merging**
