### PR TITLE
full webside code refactor

### PR DESCRIPTION
**Pull request by thelifeandtimes**
Rebuild of vaporware.network site with the following changes:
- mobile first styling using tailwind css
- removal of vue and vite dependencies/components for reduced complexity
- all content provided via markdown, including blog posts, CTA copy
- markdown styling for blog content
- refinement of waitlist form styling and submission

To-Dos
- [x] hover and active states for buttons
- [x] select explainer blog post header image
- [x] document build process and dependencies
- [x] configure vercel deployment

Future work:
- clean up of main.css file
- experiment with viewport-based sizing for certain fonts
- customization of tailwind template
- all the additional pages and nav

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
@vcavallo this is ready for your review. If it looks good, please merge to master and ensure deployment to clearweb works as expected.

**Review by vcavallo — APPROVED** [review]
Holy fucking shit, Stuart. can we hire you? This is absolutely incredible.

The icing on the cake? You actually provided a readme that explains how to run the app. I completely didn't expect that.

The only thing I might change (though I want to wait until after deploying) is the background image file size

**Comment by thelifeandtimes** [comment]
did deployment work as expected? i.e. Push to master `just works`?

and yea, lots of optimizations to be done; tomorrow I will start putting those all into issues for myself and then just work through them as other obligations allow.

**Comment by vcavallo** [comment]
@thelifeandtimes push to master just works, yup. all i did was merge to master and wait a little while.

**Pull request merged**
